# Generated by Django 2.2 on 2021-12-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="vacancy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume",
                to="vacancy.Vacancy",
            ),
        ),
    ]
